export const siteConfig = {
  name: "Rezuanul Islam Fahim",
  title: "Flutter & Full-Stack Developer",
  description:
    "Professional Flutter & Full-Stack Developer with 7+ years experience. Expert in mobile app development (iOS/Android), React/Next.js, Node.js, Firebase.",
  url: "https://www.rezuanulislamfahim.me",
  email: "rifahim98@gmail.com",
  phone: "+8801815188895",
  location: "Kishoreganj, Dhaka, Bangladesh",
  upworkUrl: "https://www.upwork.com/freelancers/~01d36b93322b73e499",
  social: {
    github: "https://github.com/Rezuanul-Islam-Fahim",
    linkedin: "https://www.linkedin.com/in/rezuanul-islam-fahim/",
    twitter: "https://x.com/rezuanul_fahim",
  },
  keywords: [
    "Flutter developer",
    "full-stack developer",
    "React developer",
    "Next.js developer",
    "mobile app development",
    "iOS developer",
    "Android developer",
    "Node.js developer",
    "TypeScript developer",
    "Firebase developer",
    "Upwork freelancer",
    "Bangladesh developer",
    "Rezuanul Islam Fahim",
  ],
};
